require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# Definición de correcciones post-install integradas directamente
def post_install_fixes(installer)
  installer.pods_project.targets.each do |target|
    # Ignorar advertencias de nullability en todos los archivos de los pods
    target.build_configurations.each do |config|
      # Deshabilitar todas las advertencias relacionadas con nullability
      config.build_settings['CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION'] = 'NO'
      config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
      config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings['CLANG_WARN_NULLABILITY_COMPLETENESS'] = 'NO'
      config.build_settings['CLANG_WARN_MISSING_NOESCAPE'] = 'NO'
      config.build_settings['CLANG_WARN_IMPLICIT_SIGN_CONVERSION'] = 'NO'
      config.build_settings['CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK'] = 'NO'
      config.build_settings['GCC_WARN_UNINITIALIZED_AUTOS'] = 'NO'
      config.build_settings['CLANG_WARN_OBJC_ROOT_CLASS'] = 'NO'
      
      # Silenciar advertencias de Swift 6
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      
      # Establecer la versión de iOS mínima a 13.0 para todos los pods
      # Esto evita advertencias relacionadas con APIs obsoletas
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
      
      # Añadir flags para suprimir TODAS las advertencias
      if config.build_settings['OTHER_CFLAGS'].nil?
        config.build_settings['OTHER_CFLAGS'] = ['$(inherited)', '-w', '-Wno-nullability-completeness', '-Wno-nullability', '-Wno-implicit-function-declaration', '-Wno-deprecated-declarations', '-Wno-everything']
      else
        # Asegurarnos de que OTHER_CFLAGS es un array
        config.build_settings['OTHER_CFLAGS'] = Array(config.build_settings['OTHER_CFLAGS'])
        config.build_settings['OTHER_CFLAGS'].concat(['-w', '-Wno-nullability-completeness', '-Wno-nullability', '-Wno-implicit-function-declaration', '-Wno-deprecated-declarations', '-Wno-everything'])
      end
      
      # Añadir flags para resolver problemas de Swift 6
      if config.build_settings['OTHER_SWIFT_FLAGS'].nil?
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-suppress-warnings']
      else
        config.build_settings['OTHER_SWIFT_FLAGS'] << '-suppress-warnings'
      end
    end
    
    # Fix for script build phase warnings by disabling dependency analysis
    if ['EXUpdates', 'React-Fabric', 'React-FabricComponents', 'hermes-engine'].include?(target.name)
      target.build_phases.each do |build_phase|
        if build_phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
          build_phase.dependency_file = nil
          build_phase.always_out_of_date = '1'
        end
      end
    end
  end
end

target 'Workproof' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    
    # Llamar a nuestras correcciones personalizadas
    post_install_fixes(installer)
  end
end
